server:
  servlet:
    url: localhost
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/retail
      auto-index-creation: true
  jackson:
    default-property-inclusion: NON_NULL
app:
  mail:
    key: "THE_KEY_TO_YOUR_THIRD_PARTY_EMAIL_PROVIDER_SENDGRID"
    from-email: "retail-app@retail.com"